openapi: 3.0.0
info:
  title: User Management System API
  version: 1.0.0
  description: API for managing users, roles, and permissions

paths:
  /auth/login:
    post:
      summary: User login
      tags: [Authentication]
  /auth/logout:
    post:
      summary: User logout
      tags: [Authentication]
  /users:
    get:
      summary: List users
      tags: [Users]
    post:
      summary: Create user
      tags: [Users]
  /users/{id}:
    get:
      summary: Get user details
      tags: [Users]
    put:
      summary: Update user
      tags: [Users]
  /roles:
    get:
      summary: List roles
      tags: [Roles]
    post:
      summary: Create role
      tags: [Roles]
  /permissions:
    get:
      summary: List permissions
      tags: [Permissions]
    post:
      summary: Create permission
      tags: [Permissions]